# coding: utf-8

"""
    Auth

    Сервис авторизации пользователей.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import auth
from auth.api.oauth_api import OauthApi  # noqa: E501
from auth.rest import ApiException


class TestOauthApi(unittest.TestCase):
    """OauthApi unit test stubs"""

    def setUp(self):
        self.api = OauthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_oauth_yandex_auth(self):
        """Test case for oauth_yandex_auth

        callback for authorise user  # noqa: E501
        """
        pass

    def test_oauth_yandex_callback(self):
        """Test case for oauth_yandex_callback

        callback for authorise user  # noqa: E501
        """
        pass

    def test_oauth_yandex_redirect(self):
        """Test case for oauth_yandex_redirect

        oauth user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
