# coding: utf-8

"""
    Auth

    Сервис авторизации пользователей.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import auth
from auth.api.logout_api import LogoutApi  # noqa: E501
from auth.rest import ApiException


class TestLogoutApi(unittest.TestCase):
    """LogoutApi unit test stubs"""

    def setUp(self):
        self.api = LogoutApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_logout_post(self):
        """Test case for logout_post

        logout user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
