# coding: utf-8

"""
    Auth

    Сервис авторизации пользователей.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import auth
from auth.api.role_api import RoleApi  # noqa: E501
from auth.rest import ApiException


class TestRoleApi(unittest.TestCase):
    """RoleApi unit test stubs"""

    def setUp(self):
        self.api = RoleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user_role(self):
        """Test case for add_user_role

        add user role  # noqa: E501
        """
        pass

    def test_del_user_role(self):
        """Test case for del_user_role

        delete user role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
