# coding: utf-8

"""
    Auth

    Сервис авторизации пользователей.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import auth
from auth.api.login_api import LoginApi  # noqa: E501
from auth.rest import ApiException


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self):
        self.api = LoginApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_2f_auth_check_post(self):
        """Test case for 2f_auth_check_post

        check multi-factor authentication code  # noqa: E501
        """
        pass

    def test_2f_auth_sync_get(self):
        """Test case for 2f_auth_sync_get

        Multi-factor authentication  # noqa: E501
        """
        pass

    def test_login_user(self):
        """Test case for login_user

        Login user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
