# coding: utf-8

"""
    Auth

    Сервис авторизации пользователей.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import auth
from auth.models.usei_id import UseiId  # noqa: E501
from auth.rest import ApiException


class TestUseiId(unittest.TestCase):
    """UseiId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUseiId(self):
        """Test UseiId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = auth.models.usei_id.UseiId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
