# coding: utf-8

"""
    Auth

    Сервис авторизации пользователей.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import auth
from auth.api.jwt_token_api import JwtTokenApi  # noqa: E501
from auth.rest import ApiException


class TestJwtTokenApi(unittest.TestCase):
    """JwtTokenApi unit test stubs"""

    def setUp(self):
        self.api = JwtTokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_user_post(self):
        """Test case for check_user_post

        validate jwt token  # noqa: E501
        """
        pass

    def test_refresh_post(self):
        """Test case for refresh_post

        refresh jwt token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
