# coding: utf-8

"""
    Auth

    Сервис авторизации пользователей.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import auth_api
from auth_api.models.user_short import UserShort  # noqa: E501
from auth_api.rest import ApiException


class TestUserShort(unittest.TestCase):
    """UserShort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserShort(self):
        """Test UserShort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = auth_api.models.user_short.UserShort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
