# coding: utf-8

"""
    Auth

    Сервис авторизации пользователей.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import auth
from auth.models.user_data import UserData  # noqa: E501
from auth.rest import ApiException


class TestUserData(unittest.TestCase):
    """UserData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserData(self):
        """Test UserData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = auth.models.user_data.UserData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
