# coding: utf-8

"""
    Auth

    Сервис авторизации пользователей.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JWTToken(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'jwt_token': 'Token',
        'refresh_token': 'Token'
    }

    attribute_map = {
        'jwt_token': 'jwt_token',
        'refresh_token': 'refresh_token'
    }

    def __init__(self, jwt_token=None, refresh_token=None):  # noqa: E501
        """JWTToken - a model defined in Swagger"""  # noqa: E501
        self._jwt_token = None
        self._refresh_token = None
        self.discriminator = None
        if jwt_token is not None:
            self.jwt_token = jwt_token
        if refresh_token is not None:
            self.refresh_token = refresh_token

    @property
    def jwt_token(self):
        """Gets the jwt_token of this JWTToken.  # noqa: E501


        :return: The jwt_token of this JWTToken.  # noqa: E501
        :rtype: Token
        """
        return self._jwt_token

    @jwt_token.setter
    def jwt_token(self, jwt_token):
        """Sets the jwt_token of this JWTToken.


        :param jwt_token: The jwt_token of this JWTToken.  # noqa: E501
        :type: Token
        """

        self._jwt_token = jwt_token

    @property
    def refresh_token(self):
        """Gets the refresh_token of this JWTToken.  # noqa: E501


        :return: The refresh_token of this JWTToken.  # noqa: E501
        :rtype: Token
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token):
        """Sets the refresh_token of this JWTToken.


        :param refresh_token: The refresh_token of this JWTToken.  # noqa: E501
        :type: Token
        """

        self._refresh_token = refresh_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JWTToken, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JWTToken):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
