# coding: utf-8

"""
    Auth

    Сервис авторизации пользователей.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class History(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'logined_by': 'float',
        'user_device_type': 'str',
        'user_agent': 'str'
    }

    attribute_map = {
        'logined_by': 'logined_by',
        'user_device_type': 'user_device_type',
        'user_agent': 'user_agent'
    }

    def __init__(self, logined_by=None, user_device_type=None, user_agent=None):  # noqa: E501
        """History - a model defined in Swagger"""  # noqa: E501
        self._logined_by = None
        self._user_device_type = None
        self._user_agent = None
        self.discriminator = None
        if logined_by is not None:
            self.logined_by = logined_by
        if user_device_type is not None:
            self.user_device_type = user_device_type
        if user_agent is not None:
            self.user_agent = user_agent

    @property
    def logined_by(self):
        """Gets the logined_by of this History.  # noqa: E501


        :return: The logined_by of this History.  # noqa: E501
        :rtype: float
        """
        return self._logined_by

    @logined_by.setter
    def logined_by(self, logined_by):
        """Sets the logined_by of this History.


        :param logined_by: The logined_by of this History.  # noqa: E501
        :type: float
        """

        self._logined_by = logined_by

    @property
    def user_device_type(self):
        """Gets the user_device_type of this History.  # noqa: E501


        :return: The user_device_type of this History.  # noqa: E501
        :rtype: str
        """
        return self._user_device_type

    @user_device_type.setter
    def user_device_type(self, user_device_type):
        """Sets the user_device_type of this History.


        :param user_device_type: The user_device_type of this History.  # noqa: E501
        :type: str
        """

        self._user_device_type = user_device_type

    @property
    def user_agent(self):
        """Gets the user_agent of this History.  # noqa: E501


        :return: The user_agent of this History.  # noqa: E501
        :rtype: str
        """
        return self._user_agent

    @user_agent.setter
    def user_agent(self, user_agent):
        """Sets the user_agent of this History.


        :param user_agent: The user_agent of this History.  # noqa: E501
        :type: str
        """

        self._user_agent = user_agent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(History, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, History):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
